default: &default
  adapter: sqlite3
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/memes-dev.sqlite3

production:
  <<: *default
  database: db/memes-prod.db

test:
  <<: *default
  database: db/memes-test.sqlite3